# Generated by Django 5.0.3 on 2024-06-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='exam',
            name='number_of_questions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
