# Generated by Django 5.0.6 on 2024-07-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
