# Generated by Django 4.2.13 on 2024-06-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('student', 'Student'), ('admin', 'Admin'), ('lecture', 'Lecture')], default='user', max_length=10),
        ),
    ]
